### ISSUE TITLE
mrview : no mouse scrolling on newer qt

### ISSUE THREAD

**Issue by samuelstjean** [MRtrix3/mrtrix3#580]
I think this would be the culprit, but I noticed that I recently lost mouse scrolling when using qt 5.6 on archlinux for going through slices. If I use the arrows everything works fine, so it is only a minor annoyance. I am currently on mrtrix 3.0.14, but it did work before and going to an older release did not seem to fix it.

Here is the config output for the other libs I am using
~~~
MRtrix build type requested: release

Detecting OS: linux
Checking for C++11 compliant compiler [g++]: 5.3.0 - tested ok
Detecting pointer size: 64 bit
Detecting byte order: little-endian
Checking for variable-length array support: yes
Checking for non-POD variable-length array support: yes
Checking for zlib compression library: 1.2.8
checking for Eigen 3 library: 3.2.8
Checking shared library generation: yes
Checking for Qt moc: moc (version 5.6.0)
Checking for Qt qmake: qmake (version 5.6.0)
Checking for Qt rcc: rcc (version 5.6.0)
Checking for Qt: 5.6.0

writing configuration to file './release/config': ok
~~~

On another computer with qt 5.4 (ubuntu 15.04) the scrolling works perfectly well, hence the may be a qt issue instead.

**Comment by jdtournier** [comment]
I can't reproduce on my system (also Arch Linux, GNOME 3.20.1 on Wayland, Qt. 5.6.0), either with the touchpad or an external mouse - everything runs fine. But on the default (Xorg, not Wayland) session, I did have to [switch to the xf86-input-libinput driver due to recent changes in GTK 3.20](https://bbs.archlinux.org/viewtopic.php?pid=1618732#p1618732) - could be related...?

**Comment by samuelstjean** [comment]
That is definitely weird then, I am also using gnome on X with libinput. I m a little bit lagging behind with 3.20.0 as I did not want to break stuff before ismrm. Might be a quirk of my configuration then, especially since we have similar setups apparently (I do not have synaptics installed, so it definitely is using libinput).

Would it be worth it to dig more (but it really seems to be a problem with a dependency more than anything)? I could give it a go in a month or so with updated libs just in case if not, or 'soon' just in case it does solve it.

**Comment by jdtournier** [comment]
You're sure you don't have a xorg.conf file or an xorg.conf.d/X-synaptics.conf file that is manually specifying the synaptics driver for your hardware...?

**Comment by samuelstjean** [comment]
So I did the update, restart, reconfig, rebuild, and unfortunately I still have the same issue.
Also made sure about the xorg.conf, I only have a /etc/X11/xorg.conf.d/30-touchpad.conf which loads libinput.

Even weirder is that all other mouse movements (changing contrasts, moving with middle click) works well, except scrolling (which works on pretty much all other programs, so probably not a mouse problem). Two finger scrolling is also not working, but is fine in chromium for example.

Part 2 :
And now I just tried to launch a wayland session, and it does work perfectly fine of course. Pretty sure it only starts the XWayland version even since I have one of those intel/nvidia hybrid laptop.

So, quirk of configuration/X11 problems I'd say, talk about weird, especially that I only seem to have the problem in mrtrix. I guess this would be overkill to find a fix (so many things could go wrong in everything I listed after all) if you want to close it.

**Comment by jdtournier** [comment]
Agreed. I'll close it with a `wontfix` - feel free to reopen of you feel there is an issue within MRtrix as such.

**Comment by samuelstjean** [comment]
A small update : turns out I accidentally touched shift while looking at stuff this morning, and it's actually shift + scroll that works perfectly fine for me to get the regular scrolling behavior. 

Not worth taking any action, but well, at least I can scroll normally on my laptop now. I must have some weird config somewhere or something, who knows.

**Comment by jdtournier** [comment]
OK, it looks like you're having similar issues to MacOSX users, which makes sense given that Wayland does provide full access to input events (as opposed to X11, which translates the events into more regular mouse events). What the shift key does is to increase the rate of scrolling 10-fold. So it looks like the events are getting through, but the increments reported are too small to trigger any actual movement. I pushed a bunch of commits recently to fix this for MacOSX users (see pull request #675), which reportedly fix this (and also add support for pinch to zoom). There was also a bug in Qt's handling which was fixed in version 5.6.1 - but since you're running Arch I assume that you'd be more up to date than that? Try updating to the latest master, see if that fixes things for you...

**Comment by samuelstjean** [comment]
Well, that was indeed exactly it. With qt 5.7.0 and mrtrix 0.3.15, I still have the bug, but the latest master is working perfectly fine on the same qt 5.7. 

Seems like something happened in qt between 5.4 and 5.7 (or ubuntu already backported it before upstream), and they did not backport the fix from 5.6. yet to 5.7, guess it will be in the first bugfix release. Anyway, all is working as intended now, so the next guy who comes with a similar problem only needs to update his stuff.

**Comment by jdtournier** [comment]
No, I doubt it's anything to do with Ubuntu's version of Qt. This is also handled differently within MRView itself now (as of last week), using Qt's new 'gestures' API. Looks like your touchpad doesn't generate 'normal' mouse events - at least on Wayland... 

In any case, good to hear it's all working!

**Comment by samuelstjean** [comment]
Ah well, actually I had the problem with my external usb mouse on X11 (wayland worked fine both touchpad and mouse if I recall correctly, but I have other generic problems with it and various software anyway), I never tried the fancy clicking/scrolling thing with the touchpad (just did now, it also works). 

So, it works fine now, it's all good, hope it does not creep up again in a different case with only touchpad or usb mouses for you guys though, thanks for fixing.
